#! /bin/bash
#
################################################################################
#  
#  grepALLhere V-1.0
#  
#  This tool search for a string in all files and directories below current
#  directory.
#
################################################################################
#  
#  Copyright (C) 2011 by Johannes Storm <jo-master@gmx.de>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#  General Public License for more details.
#  
#  
#  use:
#  - copy this script in Nautilus Script folder and make it executable
#  - in Nautilus select a directory and run this script from context menu
#  - enter the keywords
#  
#  
#  required software:
#  - coreutils
#  - zenity
#  
################################################################################

# check for zenity
gui=$(which zenity)
if [ ! -x "$gui" ];
then
    echo "Zenity is required: 'sudo apt-get install zenity"
    exit 0
fi


# ask for search string
SEARCHSTRING=$(zenity --entry \
                      --text "Search String" \
                      --title "Search for a string" \
                      --width="500")
if [ -z "${SEARCHSTRING}" ];
then
    exit 0
fi


# try to find something
find ./ -type f -exec grep -q "${SEARCHSTRING}" {} \; -print |\
  tee >(sleep 1; zenity --progress --title="Searching ..." --pulsate --auto-close) |\
  zenity --text-info --title "Search Results" --width="500" --height="500"


exit 0

