#!/bin/sh
##
## Nautilus
## SCRIPT: 00_list_hiddenDirs.sh
##
## PURPOSE: Lists ALL 'hidden' directories under a directory
##          and shows the list in an editor of your choice.
##
## HOW TO USE: In Nautilus, select any file in the directory. Then
##             right-click and choose this Nautilus script to run.
##
## Started: 2010mar09
## Changed: 2010apr07 Chgd the way the OUTFILE is handled ---
##                    puts it in /tmp if no write permission
##                    to the 'current' (Nautilus) directory.
## Changed: 2010apr11 Touched up the comment statements.


## FOR TESTING:
# set -v
# set -x

############################
## Prepare the output file.
############################

CURDIR="`pwd`"

OUTFILE="00_temp_hiddenDirs.lis"
if test ! -w "$CURDIR"
then
   OUTFILE="/tmp/$OUTFILE"
fi

if test -f "$OUTFILE"
then
   rm -f "$OUTFILE"
fi


################################
## Generate heading for the list.
################################

DATETIME=`date '+%Y %b %d  %a  %T%p'`

echo "\
..................... $DATETIME ............................
'HIDDEN' DIRECTORIES under the directory

   $CURDIR

...........................................................................
" > "$OUTFILE"


######################
## Generate the list.
######################

ls -A -F -R | grep '/$' | grep '^\.' >> "$OUTFILE"

## The following SHOWS '.' and '..' subdirs:
#  find . -type d -name '.*' -print >> "$OUTFILE"


##################################
## Generate trailer for the list.
##################################
BASENAME=`basename $0`
DIRNAME=`dirname $0`

echo "
...........................................................................

This list was generated by script
   $BASENAME
in directory
   $DIRNAME

It ran the command

   ls -A -F -R | grep '/$' | grep '^\.'

to find just the *hidden directories*.

..................... $DATETIME ............................
" >> "$OUTFILE"


######################
## Show the list.
######################

. $HOME/.gnome2/nautilus-scripts/.set_VIEWERvars.shi

$TXTVIEWER "$OUTFILE" &

