#!/bin/sh
##
## Nautilus
## SCRIPT: 00_list_allOfDirs_1lev.sh
##
## PURPOSE: Lists ALL directories in a directory (including the
##          'hidden' directories) and shows the list in an editor
##          of your choice.
##
## HOW TO USE: In Nautilus, select any file in the directory. Then
##             right-click and choose this Nautilus script to run.
##
## Created: 2010mar09
## Changed: 2010apr11 Touched up comment statements. Added logic to
##                    determine the directory for the OUTFILE.
## Changed: 2010sep17 Added header and trailer to listing.

## FOR TESTING:
# set -v
# set -x

##############################################
## Prepare the output file.
##
## If the user has write-permission on the
## current directory, put the file in the pwd.
## Otherwise, put the file in /tmp.
##############################################

CURDIR="`pwd`"

OUTFILE="00_temp_dirsLIST.txt"
if test ! -w "$CURDIR"
then
  OUTFILE="/tmp/$OUTFILE"
fi

if test -f "$OUTFILE"
then
  rm -f "$OUTFILE"
fi


#####################################
## Generate a heading for the list.
#####################################

DATETIME=`date '+%Y %b %d  %a  %T%p'`

echo "\
..................... $DATETIME ............................

Current directory: $CURDIR

List of  DIRECTORIES-ONLY  there-under follows
--- ONE-LEVEL only.

...........................................................................
" >  "$OUTFILE"


#################################
## Generate the list.
##
##  The '-F' parm shows directories
##  with an ending slash.
#################################

ls -a -F | grep '/$'  >> "$OUTFILE"


#####################################
## Generate a trailer for the list.
#####################################
BASENAME=`basename $0`
DIRNAME=`dirname $0`

echo "
...........................................................................

This list was generated by script
   $BASENAME
in directory
   $DIRNAME

Used command
     ls -a -F | grep '/$'

..................... $DATETIME ............................
" >>  "$OUTFILE"


#######################
## Show the list.
#######################

. $HOME/.gnome2/nautilus-scripts/.set_VIEWERvars.shi

$TXTVIEWER "$OUTFILE" &

