#!/bin/sh
##
## Nautilus
## SCRIPT: 00_list_allOfDirFiles_1lev.sh
##
## PURPOSE: Lists ALL files in a directory and shows the list
##          in an editor of your choice.
##
## HOW TO USE: In Nautilus, select any file in the directory. Then
##             right-click and choose this Nautilus script to run.
##
## Started: 2010mar09
## Changed: 2010apr04 Used 'ls -a -F' to separate directories
##                    from files --- and show hidden files.
## Changed: 2010apr11 Touched up the comments. Added logic to
##                    determine the directory for the OUTFILE.
## Changed: 2010sep17 Added header and trailer to listing. 

## FOR TESTING:
# set -v
# set -x

##############################################
## Prepare the output file.
##
## If the user has write-permission on the
## current directory, put the file in the pwd.
## Otherwise, put the file in /tmp.
##############################################

CURDIR="`pwd`"

OUTFILE="00_temp_dirFilesLIST.txt"
if test ! -w "$CURDIR"
then
  OUTFILE="/tmp/$OUTFILE"
fi

if test -f "$OUTFILE"
then
  rm -f "$OUTFILE"
fi


#####################################
## Generate a heading for the list.
#####################################

DATETIME=`date '+%Y %b %d  %a  %T%p'`

echo "\
..................... $DATETIME ............................

Current directory: $CURDIR

List of files (and directories) there-under follows
--- ONE-LEVEL only.

...........................................................................
" >  "$OUTFILE"


#################################################################
## Generate the list.
##
##  The '-F' parm shows directories with an ending slash
##  and it shows execute-permission files with an ending asterisk.
#################################################################

## Show the directories, then the non-directories.
ls -a -F | grep '/$' >> "$OUTFILE"
ls -a -F | grep -v '/$' >> "$OUTFILE"

## A simple alternative which mixes directories and regular-files.
# ls  > "$OUTFILE"


#####################################
## Generate a trailer for the list.
#####################################
BASENAME=`basename $0`
DIRNAME=`dirname $0`

echo "\
.......................................................................

This list was generated by script
   $BASENAME
in directory
   $DIRNAME

Used commands
     ls -a -F | grep '/$' (to show directories first)
and
     ls -a -F | grep -v '/$' (to show non-directories)

Asterisk (*) indicates files with execute permission.

..................... $DATETIME ............................
" >>  "$OUTFILE"


###################
## Show the list.
###################

. $HOME/.gnome2/nautilus-scripts/.set_VIEWERvars.shi

$TXTVIEWER "$OUTFILE" &


