#! /bin/bash
# Use /usr/local/bin/bash on FreeBSD

ZENITY=$(which zenity)

$ZENITY --info --text="$*"

$ZENITY --info --text="NAUTILUS_SCRIPT_SELECTED_FILE_PATHS = $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"
$ZENITY --info --text="NAUTILUS_SCRIPT_SELECTED_URIS = $NAUTILUS_SCRIPT_SELECTED_URIS"
$ZENITY --info --text="NAUTILUS_SCRIPT_CURRENT_URI  = $NAUTILUS_SCRIPT_CURRENT_URI"
$ZENITY --info --text="NAUTILUS_SCRIPT_WINDOW_GEOMETRY = $NAUTILUS_SCRIPT_WINDOW_GEOMETRY"

