#!/bin/sh
##
## NAUTILUS
## SCRIPT: 00_list_softwarePackages_dpgk-l.sh
##
## PURPOSE: List software packages installed on this host computer
##          --- using 'dpkg -l'.
##
## HOW TO USE: Click on the name of any file (or directory) in a Nautilus
##             directory list.
##             Then right-click and choose this script to run (name above).
##
## Created: 2010may12
## Changed:

## FOR TESTING:
#  set -v
#  set -x

##############################################################
## Prep a temporary filename, to hold the list of filenames.
##      We put the output file in /tmp, in case the user
##      does not have write-permission in the current directory,
##      and because the output does not, usually, have anything
##      to do with the current directory.
#############################################################

# OUTFILE="00_list_softwarePackages_dfk-l.lis"
  OUTFILE="/tmp/00_list_softwarePackages_dfk-l.lis"
 
  if test -f "$OUTFILE"
  then
     rm -f "$OUTFILE"
  fi

###################
## Prepare the list.
###################

THISHOST=`hostname`

echo "\
................ `date '+%Y %b %d  %a  %T%p %Z'` ......................

Software Packages (per 'dpkg -l)
--- for host:  $THISHOST


Some more information is at the bottom of this list.

------------------------------------------------------------------------------
" > "$OUTFILE"


EXECHECK=`which dpkg`

if test -f "$EXECHECK"
then
    echo "
####
dpkg :
####
" >> "$OUTFILE"
    dpkg -l >> "$OUTFILE"
fi


#################
## ADD Trailer
#################

echo "
................ `date '+%Y %b %d  %a  %T%p %Z'` ......................

  The list above was generated by the script

$0

  If you want to add more software info via more commands,
  you can simply edit the script.

------------------------------------------------------------------------------
FOR MORE INFO ON THESE EXECUTABLES:

For some of these topics (or commands like 'dpkg'),
you can type 'man <topic-name>' to see details on the topic.
    ('man' stands for Manual.  It gives you a user manual 
     for a command/utility/protocol/topic.)

You can type 'man man' at a shell prompt to see a description of
the 'man' command.

Or use the 'show_manhelp_4topic' Nautilus script in the
'LinuxHELPS' group of Nautilus scripts.


******* END OF LIST of hardware info on host $THISHOST *******
" >> "$OUTFILE"


#########################################################
## Show the list of software packages - 'dpkg -l' output.
#########################################################
   
. $HOME/.gnome2/nautilus-scripts/.set_VIEWERvars.shi

$TXTVIEWER "$OUTFILE" &

